### PR TITLE
Fixes for trace examples

### LINKED ISSUE #156: Traces are not exported to Zepkin or Jaeger
I tried to run the examples given. After cloning the repo, I tried `make install` and `make examples`. It ran as expected and I got the following result

```
Starting opentelemetry-php_php_1 ... done
docker-compose run --rm php php ./examples/AlwaysOnTraceExample.php
Starting AlwaysOnTraceExample
Trace with id cdfb6291b47a3778c064cc8e4630381f started
AlwaysOnTraceExample complete!  See the results at http://localhost:9411/
docker-compose run --rm php php ./examples/AlwaysOffTraceExample.php

Sampling is not enabled
docker-compose run --rm php php ./examples/JaegerExporterExample.php
Starting JaegerExporterExample
Trace with id 055a2bd2c567e478bdfb4c0ee4ad26be started
JaegerExporterExample complete!  See the results at http://localhost:16686/
```

**What is the expected behavior?**
See the traces in Zepkin or Jaeger

**What is the actual behavior?**
There are no traces in http://localhost:9411/zipkin/ or http://localhost:16686/search

Following is my PHP Version.
`PHP 7.3.11 (cli) (built: Apr 17 2020 19:14:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies`

### PR DESCRIPTION
**Pull request by artem-prozorov**
Closes #156 

The idea is to change default span context behavior so that the first context is sampled by default

### CODE REVIEW

File: sdk/Trace/SpanContext.php [hunk 1]
```diff
@@ -86,6 +86,17 @@ public static function generate(bool $sampled = false): SpanContext
         return self::fork(self::randomHex(16), $sampled);
     }
 
+    /**
+     * Creates a new sampled context with random trace
+     *
+     * @param boolean $sampled Default: false
+     * @return SpanContext
+     */
+    public static function generateSampled(): SpanContext
```
Comment (artem-prozorov) [inline sdk/Trace/SpanContext.php:95]: Just decided to add this to increase readability so one doesn't have to guess what is "true" in `SpanContext::generate(true);`

File: tests/Sdk/Unit/Trace/SpanContextTest.php [hunk 2]
```diff
@@ -31,18 +31,22 @@ public function testSpanContextCanCreateSampledSpans()
...
      */
-    public function testDefaultSpansFromTracerAreNotSampled()
+    public function testDefaultSpansFromTracerAreSampled()
     {
         $tracer = $this->getTracer();
 
         $span = $tracer->startAndActivateSpan('test');
 
-        $this->assertFalse($span->isSampled());
+        $this->assertTrue($span->isSampled());
```
Comment (artem-prozorov) [inline tests/Sdk/Unit/Trace/SpanContextTest.php:49]: I'm not sure about this. Actually this PR will change the default behavior(prior to this new spans were not sampled).
Is this a logic breaking change?

Comment (bobstrecansky) [reply tests/Sdk/Unit/Trace/SpanContextTest.php:49]: It looks like the default sampler was declared to be `ParentOrElse(AlwaysOn)` - that was changed 3 days ago:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#built-in-samplers

I think this behaviour is fine for now.  We can always change it later if need be.
