### PR TITLE
fixing BC alias for InstrumentationLibrary

### LINKED ISSUE #702: InstrumentationScope Alias
We should make an alias for `InstrumentationScope` to `InstrumentationLibrary`, so if anyone calls the previous {deprecated} function, we can maintain backwards compatibility.

### PR DESCRIPTION
**Pull request by brettmc**
Correctly aliasing the renamed InstrumentationLibraryInterface to the new InstrumentationScopeInterface
Fixes #702

### CODE REVIEW

**Review by bobstrecansky — APPROVED** [review]
Approving but Brett also mentioned double checking with @tidal

File: src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php [hunk 1]
```diff
@@ -13,7 +13,7 @@ interface InstrumentationLibraryInterface extends Moved
 /**
  * @codeCoverageIgnoreStart
  */
-class_alias(Moved::class, 'OpenTelemetry\SDK\InstrumentationLibraryInterface');
+class_alias(InstrumentationLibraryInterface::class, 'OpenTelemetry\SDK\InstrumentationLibraryInterface');
```
Comment (tidal) [inline src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php:16]: This should point to `'OpenTelemetry\SDK\Common\Instrumentation\InstrumentationLibraryInterface'` as this was the most recent change. 
```php
class_alias(InstrumentationLibraryInterface::class, 'OpenTelemetry\SDK\Common\Instrumentation\InstrumentationLibraryInterface');
```

Comment (brettmc) [reply src/SDK/Common/Dev/Compatibility/BC/InstrumentationLibraryInterface.php:16]: Ah, ok, I was going for BC to the original location. Lucky I checked with you.
```suggestion
class_alias(InstrumentationLibraryInterface::class, 'OpenTelemetry\SDK\Common\Instrumentation\InstrumentationLibraryInterface');
```
